# Generated by Django 5.1.1 on 2024-10-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevBaseAlpha',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='开发信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '开发信息',
                'verbose_name_plural': '开发信息',
            },
        ),
        migrations.CreateModel(
            name='FeatureBaseR',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('status_decision', models.TextField(verbose_name='状态决策')),
                ('status_detail', models.TextField(verbose_name='状态详情')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='评论讨论')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
            ],
            options={
                'verbose_name': '已处理特性',
                'verbose_name_plural': '已处理特性',
            },
        ),
        migrations.CreateModel(
            name='FeatureBaseRaw',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='原始内容')),
                ('summary', models.TextField(verbose_name='内容摘要')),
                ('source', models.TextField(verbose_name='来源')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='评论')),
                ('publicable', models.BooleanField(default=True, verbose_name='是否公开')),
                ('meta_features', models.TextField(blank=True, null=True, verbose_name='元特性')),
            ],
            options={
                'verbose_name': '原始特性',
                'verbose_name_plural': '原始特性',
            },
        ),
        migrations.CreateModel(
            name='MacroBaseAlpha',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='宏观信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '宏观信息',
                'verbose_name_plural': '宏观信息',
            },
        ),
    ]
