# Generated by Django 5.1.1 on 2024-10-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_featurebaser_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurebaser',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featurebaser',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='featurebaser',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featurebaseraw',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
