# Generated by Django 5.1.1 on 2024-10-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_featurebaserawurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureBaseRawUrl',
        ),
    ]
